### PR TITLE
Disable feature selection while drawing

### LINKED ISSUE #105: prevent selecting of features while drawing
When drawing a new feature geometry we need to prevent existing features from being selected like this:
image

### PR DESCRIPTION
**Pull request by stdavis**
Closes #105

### CODE REVIEW

**Comment by steveoh** [comment]
you are still able to click on adjacent features.

**Comment by steveoh** [comment]
otherwise this does what it says so rebase master and :shipit:

**Comment by stdavis** [comment]
Just pushed another commit that disables clicking on adjacent features. Do you want to review again?

**Comment by steveoh** [comment]
merged

**Pull request closed without merging**
