### PR TITLE
Scheduled script for updating reference layer data

### PR DESCRIPTION
**Pull request by stdavis**
Related to #166

### CODE REVIEW

**Comment by steveoh** [comment]
please create a readme with how to deploy this and we can go from there.

**Comment by stdavis** [comment]
> please create a readme with how to deploy this and we can go from there.

Addressed with f3fec50

**Comment by stdavis** [comment]
For bringing in the `agrc` package would you want a `Requirements.txt` or a `setup.py`?

**Comment by steveoh** [comment]
a requirements is more appropriate

**Comment by stdavis** [comment]
> a requirements is more appropriate

Addressed with: 3178afc

**Comment by stdavis** [comment]
@steveoh Did you want me to push this to the dev server? If so, can this PR be merged?

**Comment by steveoh** [comment]
Yes push this to the dev server and make sure all is well and merge if you are happy with the how it goes, installation instructions, etc

**Comment by stdavis** [comment]
Pushed to dev server with no issues. Let me know if you want me to push to production or wait.

**Comment by steveoh** [comment]
If it is working with no issues, I see no reason to wait.

**Comment by stdavis** [comment]
Done.

On Mon, Dec 14, 2015 at 8:41 AM, steveoh <notifications@github.com> wrote:

> If it is working with no issues, I see no reason to wait.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/wri-web/pull/175#issuecomment-164470569>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@SThomasDavis <https://twitter.com/SThomasDavis>

**Pull request merged**
