### PR TITLE
Ref layers update

### LINKED ISSUE #121: update/add reference layers
From Nathan:
>After some discussion down here, I'd like to request a change to one of the reference data layers on the WRI app. I had previously asked for the Fire Threat Index from Forestry, Fire, and State Lands, but have determined that the Fire RISK Index is the more proper data layer to show. The data set can be found at the following link. The integer values 1 through 9 should work well to associate with the colors for indexing. I apologize for this change. Please let me know if you have an issues with this, need more information, questions, etc. 

>http://utahdnr.maps.arcgis.com/home/item.html?id=2c95d3ddfd6e4b05a8b2ebf46e030b39

Also add the streams layer that @steveoh added to the reference layers mxd with scale dependencies.

### PR DESCRIPTION
**Pull request by stdavis**
Closes #121

Waiting to hear back from Eric on enabling SSL on maps.dnr.utah.gov.

### CODE REVIEW

**Comment by stdavis** [comment]
Now waiting on Buck to build this service on his server.

**Comment by stdavis** [comment]
Buck said that Sean would have the new service built by the end of this week.

**Comment by stdavis** [comment]
@steveoh This is finally read for your review.

**Comment by steveoh** [comment]
NHD has scale dependency although the button does not indicate that and users can click it and nothing happens.

**Comment by stdavis** [comment]
Addressed with 0037846

**Pull request closed without merging**
