### PR TITLE
add optional description to feature details

### PR DESCRIPTION
**Pull request by steveoh**

### CODE REVIEW

**Comment by stdavis** [comment]
How long are descriptions? I was thinking that maybe it should be put in a `<p>` something like this:
```html
<label>Description</label>
<br>
<p>{{description}}</p>
```

But maybe they are not too long?

**Comment by steveoh** [comment]
average is 19 characters. max is 178 with the field size set to 255. I do not think that we need the line break. Here is an example of the longest current one.

image

**Comment by stdavis** [comment]
I'm good with that.

**Comment by stdavis** [comment]
Merged in: a5b7705

**Pull request closed without merging**
