### PR TITLE
Fix bug preventing feature select via map click

### LINKED ISSUE #99: Can't select features by clicking on the map

### PR DESCRIPTION
**Pull request by stdavis**
Also made cursor into pointer for project feature layers.

Fixes #99

### CODE REVIEW

**Comment by steveoh** [comment]
can you explain how changing to a instance variable fixes the bug? Context issue?

**Comment by steveoh** [comment]
can you explain why changing to a global fixes this? Also will you check the why the dojo build failed

**Comment by stdavis** [comment]
No 100% sure why but something to do with the collection on the grid already having a filter applied to show only the parents. It already had something like `parent = null`. When I tried to query it for the specific child feature that was clicked on the map it would combine that query with the `parent = null` query which resulted in no data.

The only way that I could get it to work was to query the original store that the grid collection was built off of.

I restarted the build. If it fails again I'll check it in the morning.

**Comment by stdavis** [comment]
@steveoh Build is fixed.

**Pull request merged**
