### PR TITLE
Introduce SummaryReportMap GP Service

### PR DESCRIPTION
**Pull request by stdavis**
Still waiting on Casey to try this out. There will likely be tweaks but wanted to get this out there for @steveoh to take a look at and make sure that I'm not going off the rails on anything.

Closes: https://redmine.dts.utah.gov/issues/38649

- [ ] Update the deploy notes on the wiki before this PR is accepted.

### CODE REVIEW

**Comment by steveoh** [comment]
How about putting the wiki notes in here and we would be able to copy them over and I would know how to pubilsh this :)

**Comment by steveoh** [comment]
Seems minimal which is what they have asked for. Two things:

1. Allow for dts to send in at least width in pixels and control the aspect ratio in code or allow for both if server handles the extent properly. 

1. Label the features by feature id. 

There is going to be more with this as time goes on, so let's build this with the mentality for easy enhancements.

**Comment by stdavis** [comment]
> Allow for dts to send in at least width in pixels and control the aspect ratio in code or allow for both if server handles the extent properly.

Addressed in 96edd15

> Label the features by feature id.

Addressed in 635dee8

**Comment by steveoh** [comment]
this is in DEV and AT so it should be in master.

**Pull request closed without merging**
