### PR TITLE
Post data to new features service

### PR DESCRIPTION
**Pull request by stdavis**
I think that this is pretty close pending how we pass any confirmation message back from the api. Although given how far behind we are on this project maybe it's good enough for now.

### CODE REVIEW

**Comment by steveoh** [comment]
somehow I just ended up like this switching projects on this branch.

image

**Comment by stdavis** [comment]
> somehow I just ended up like this switching projects on this branch.

That's not good. Can you give me steps to reproduce?

**Comment by steveoh** [comment]
it may have been i clicked on an id on the map. lets say 1. then changed the id to 2 and possibly to trigger the bug, while 2's xhr was in flight, switched the url to project 3.

**Comment by stdavis** [comment]
I tried but was unable to reproduce. My project requests are too fast to try to switch while one is in progress. However, I just pushed a commit that attempts to prevent this bug. Update and let me know if it's still happening.

**Pull request merged**
