### PR TITLE
add CLI with configurations to BuildJSON

### LINKED ISSUE #142: build_json.py grunt task & schedule
Wire up a grunt task to be included in the build process to run `build_json.py` against dev or at.

Also look at scheduling this task to run regularly on the server.

### PR DESCRIPTION
**Pull request by steveoh**
closes #142

### CODE REVIEW

**Comment by steveoh** [comment]
@stdavis it stinks that this fails because the build pipeline calls build:prod. Is there a better idea than to copy build prod items without shell for travis?

**Comment by stdavis** [comment]
Maybe have a separate build task for travis? Just one to run the dojo build system?

**Comment by stdavis** [comment]
What about something like that?

**Comment by steveoh** [comment]
That is super cool. Where is the docs on that? Somewhere in Travis? :shipit:

**Comment by stdavis** [comment]
http://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

On Fri, Oct 23, 2015 at 9:51 AM, steveoh <notifications@github.com> wrote:

> That is super cool. Where is the docs on that? Somewhere in Travis? [image:
> :shipit:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/wri-web/pull/146#issuecomment-150614025>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@SThomasDavis <https://twitter.com/SThomasDavis>

**Comment by stdavis** [comment]
I'm good to with this PR. I'd be happy to squash my commits and :shipit: pending @steveoh's buy off.

**Pull request merged**
