### PR TITLE
validate form on comments keyup in addition to change

### LINKED ISSUE #135: validate new feature form on keydown in comments
Currently if you type data into the comments field the save button is not enabled until you move focus out of the comments field. This is awkward since the user can't click on the save button.
image

### PR DESCRIPTION
**Pull request by stdavis**
Fixes #135

### CODE REVIEW

**Comment by steveoh** [comment]
does this handle copy paste? You might [consider this approach](https://github.com/agrc/Crash-web/blob/952673a07573ba1d8502c57d7ec55ad05de9ecf5/src/app/FilterDateTime.js#L50-L56)

**Comment by stdavis** [comment]
Addressed. Thanks for the reminder.

**Comment by steveoh** [comment]
:shipit:

**Comment by steveoh** [comment]
merged 50c1df9d3c68596b5a914abfa799f00ea3a0fd85

**Pull request closed without merging**
